- README.md
- ramls/examples/template.sample
- ramls/examples/templateProcessingRequest.sample
- ramls/examples/templateProcessingResult.sample
- ramls/examples/templatesCollection.sample
- src/main/resources/templates/db_scripts/populate-templates.sql
> Moving to MIME type

- src/main/java/org/folio/template/resolver/MustacheTemplateResolver.java
- src/main/java/org/folio/template/service/TemplateServiceImpl.java
- src/test/java/org/folio/rest/impl/TemplateRequestTest.java
MODSENDER-3 Fixing null pointer exception when passing request without context
> MODSENDER-3 Fixing null pointer exception

- src/main/resources/templates/db_scripts/populate-templates.sql
UIU-511 UIU-512 Create password email and reset password email templates added to pre-populate script.
> UIU-511 UIU-512 Templates added to pre-populate script

- src/main/resources/templates/db_scripts/populate-templates.sql
UIU-737 UIU-738 "Password is successfully created email" and "Username located email" templates added to pre-populate script
> UIU-737 UIU-738 Templates added to pre-populate script

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/template-engine.raml
- src/main/java/org/folio/rest/impl/TemplateResourceImpl.java
- src/main/java/org/folio/template/InUseTemplateException.java
- src/main/java/org/folio/template/client/CirculationStorageClient.java
- src/main/java/org/folio/template/service/TemplateService.java
- src/main/java/org/folio/template/service/TemplateServiceImpl.java
- src/main/java/org/folio/template/util/TemplateEngineHelper.java
- src/test/java/org/folio/rest/impl/TemplateDeletionTest.java
Resolves: MODTEMPENG-14
Not allow user to delete patron notice template thru API (backend) if currently in use
https://issues.folio.org/browse/MODTEMPENG-14
> [MODTEMGENG-14] Forbid in use templates deletion

- pom.xml
- src/main/java/org/folio/template/resolver/MustacheTemplateResolver.java
- src/test/java/org/folio/rest/impl/RestVerticleTest.java
- src/test/java/org/folio/rest/impl/TemplateRequestTest.java
Resolves: MODTEMPENG-21
Process template endpoint responds with Internal server error
https://issues.folio.org/browse/MODTEMPENG-21
> [MODTEMPENG-21] Allow to process templates with array in context

- pom.xml
> [MODTEMPENG-22] Fix security vulnerabilities reported in jackson-databind

- src/main/java/org/folio/template/util/ContextDateTimeFormatter.java
- src/test/java/org/folio/rest/impl/TemplateRequestTest.java
- src/test/java/org/folio/template/util/ContextDateTimeFormatterTest.java
Add JsonArray case into dates localization
Resolves: [MODTEMPENG-23](https://issues.folio.org/browse/MODTEMPENG-23)
> [MODTEMPENG-23] Dates are not localized in context containing arrays

- pom.xml
- src/main/java/org/folio/template/service/TemplateServiceImpl.java
- src/main/java/org/folio/template/util/ContextDateTimeFormatter.java
- src/main/java/org/folio/template/util/TemplateEngineHelper.java
- src/test/java/org/folio/rest/impl/TemplateRequestTest.java
- src/test/java/org/folio/template/util/ContextDateTimeFormatterTest.java
- src/test/java/org/folio/template/util/TemplateEngineHelperTest.java
**Purpose**
Add additional rules for formatting dates in patron notices.
**Link**
[MODTEMPENG-33](https://issues.folio.org/browse/MODTEMPENG-33)
> [MODTEMPENG-33] Update tokens to only show date

- Dockerfile
- Jenkinsfile
- pom.xml
- upgrade to jdk 11;
- upgrade RMB to 31.0.2
Resolves: [MODTEMPENG-56](https://issues.folio.org/browse/MODTEMPENG-56)
> MODTEMPENG-56 update RMB to 31.0.2 and JDK11

- pom.xml
Resolves: [MODTEMPENG-60](https://issues.folio.org/browse/MODTEMPENG-60)
> [MODTEMPENG-60] Upgrade to RMB 31.1.5 and Vert.x 3.9.4

- src/main/java/org/folio/template/util/ContextDateTimeFormatter.java
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/update-password-changed-template.sql
- src/test/java/org/folio/template/util/ContextDateTimeFormatterTest.java
Update password-changed template to have date and time in an email notification.
* Update template
* Update logic of dateTimes parsing
> MODTEMPENG-59 Update password-changed template

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/template/util/BarcodeImageGenerator.java
- src/main/java/org/folio/template/util/ContextDateTimeFormatter.java
- src/main/java/org/folio/template/util/TemplateEngineHelper.java
- src/test/java/org/folio/rest/impl/ApiTestHelper.java
- src/test/java/org/folio/rest/impl/RestVerticleTest.java
- src/test/java/org/folio/rest/impl/TemplateDeletionTest.java
- src/test/java/org/folio/rest/impl/TemplateRequestTest.java
- src/test/resources/log4j2-test.properties
Resolves: [MODTEMPENG-63](https://issues.folio.org/browse/MODTEMPENG-63)
> MODTEMPENG-63 Upgrade to RMB v32

- pom.xml
- src/test/java/org/folio/rest/impl/Postgres.java
Resolves: [MODTEMPENG-69](https://issues.folio.org/browse/MODTEMPENG-69)
> MODTEMPENG-69 Update RMB and Vertx versions

- NEWS.md
- pom.xml
Resolves [MODTEMPENG-71](https://issues.folio.org/browse/MODTEMPENG-71)
> [MODTEMPENG-71] Release 1.14.0

- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/update-automated-fee-fine-category.sql
- src/test/java/org/folio/migration/TemplatesMigrationTest.java
Resolves https://issues.folio.org/browse/MODTEMPENG-72.
> [MODTEMPENG-72] Create migration script for no longer supported template category

- NEWS.md
- pom.xml
Resolves [MODTEMPENG-73](https://issues.folio.org/browse/MODTEMPENG-73).
> [MODTEMPENG-73] Release 1.15.0

- pom.xml
Resolves: https://issues.folio.org/browse/MODTEMPENG-79.
> MODTEMPENG-79

- NEWS.md
- pom.xml
> Release 1.16.0

- pom.xml
[MODTEMPENG-84](https://issues.folio.org/browse/MODTEMPENG-84)
_Module can not be compiled twice without clean_
> MODTEMPENG-84: Module can not be compiled twice without clean

- pom.xml
[MODTEMPENG-89](https://issues.folio.org/browse/MODTEMPENG-89)
> [MODTEMPENG-89] Upgrade to RMB 35.0.0 and Vertx 4.3.3

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODTEMPENG-91
> MODTEMPENG-91: Release 1.18.0

- PULL_REQUEST_TEMPLATE.md
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/impl/TemplateRequestImpl.java
- src/main/java/org/folio/rest/impl/TemplateResourceImpl.java
- src/main/java/org/folio/template/client/CirculationStorageClient.java
- src/main/java/org/folio/template/client/ConfigurationClient.java
- src/main/java/org/folio/template/dao/TemplateDaoImpl.java
- src/main/java/org/folio/template/resolver/MustacheTemplateResolver.java
- src/main/java/org/folio/template/service/TemplateServiceImpl.java
- src/main/java/org/folio/template/util/BarcodeImageGenerator.java
- src/main/java/org/folio/template/util/ContextDateTimeFormatter.java
- src/main/java/org/folio/template/util/TemplateContextPreProcessor.java
- src/main/java/org/folio/template/util/TemplateEngineHelper.java
MODTEMPENG-80 (https://issues.folio.org/browse/MODTEMPENG-80) 
Adding loggers as part of logging improvements
_By following the practices mentioned in https://wiki.folio.org/display/DD/Logging,
Added loggers wherever needed._
> MODTEMPENG-80 Logging improvement

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
To release for poppy
Follow release instructions
> MODTEMPENG-98 - Poppy release

- NEWS.md
- pom.xml
Poppy release with upgraded RMB version.
> MODTEMPENG-98 - Poppy release with upgraded RMB version.

- src/main/resources/templates/db_scripts/populate-templates.sql
> [MODTEMPENG-101]-updated template body

- pom.xml
- src/main/java/org/folio/rest/impl/TemplateResourceImpl.java
…versions
The purpose of the PR is to implement MODTEMENG-103
We have upgraded raml,vertx and other dependencies versions for Quesnelia
> MODTEMPENG-103 Updating dependencies for quesnelia

- NEWS.md
- pom.xml
> [MODTEMPENG-102]-tmp release 1.20.0

- .github/workflows/postgres.yml
- pom.xml
- src/main/java/org/folio/rest/impl/TemplateResourceImpl.java
- src/test/java/org/folio/rest/impl/BarcodeIT.java
> [MODTEMPENG-107] - Upgrade RMB version to 35.3.0

- NEWS.md
- pom.xml
> MODTEMPENG-109 Ramsons release

- .github/workflows/postgres.yml
- Dockerfile
- Jenkinsfile
- pom.xml
> FOLIO-4220 - Java and rmb version upgrade

- NEWS.md
- pom.xml
> Update NEWS.md and versions

- NEWS.md
- pom.xml
> Update pom version
